pod 'AFNetworking', '~> 3.0'
pod 'vfrReader','~> 2.8.6'
pod 'ZipUtilities'
pod 'SDWebImage','~> 3.7'
pod 'MRProgress'
pod 'FMDB'
pod 'StreamingKit'
pod 'SCLAlertView-Objective-C'
pod 'FXKeychain'
pod 'DAProgressOverlayView'
pod 'MuPDF'

